#!/bin/sh

# maybe add some sort of startepage idk

show_help() {
    printf "
    Usage:
      %s [option]
    
    Options:
      sofa            sofa
      setup           Setup sofa 
      
      wall -r         Set random wallpaper
      wall -i <image> Set wallpaper from image
    \n" "${0##*/}"
}

if [ "$1" == "--help" ]; then

    show_help
    exit 0

fi

if [ "$1" == "sofa" ]; then

    echo "sofa"

elif [ "$1" == "setup" ]; then

    mkdir -p ~/.sofa
    mkdir -p ~/.sofa/templates
    cp .sofa/sofa.py ~/.sofa/sofa.py
    cp .sofa/config.json ~/.sofa/config.json

elif [ "$1" == "wall" ]; then

    wall_path=$(jq -r '.wallpath' ~/.sofa/config.json)

    if [ "$2" == "-r" ]; then

        wall_file=$(ls "$HOME/$wall_path/" | shuf -n 1)
        cp "$HOME/$wall_path/$wall_file" "$HOME/$wall_path/wallpaper"
        pkill hyprpaper && hyprpaper &
        disown %1

    elif [ "$2" == "-i" ]; then

        cp "$HOME/$wall_path/$3" "$HOME/$wall_path/wallpaper"
        pkill hyprpaper && hyprpaper &
        disown %1

    else

        selected_wallpaper=$(find "$HOME/$wall_path" -type f | fzf --preview 'kitty icat {}')

        if [ -n "$selected_wallpaper" ]; then

            cp "$selected_wallpaper" "$HOME/$wall_path/wallpaper"
            pkill hyprpaper && hyprpaper &
            disown %1

        fi
    fi

# Random Utils
elif [ "$1" == "utils" ]; then

    if [ "$2" == "-r" ]; then
        yay -S cbonsai cmatrix neofetch hyfetch pipes.sh cava uwufetch
    elif [ "$2" == "-i" ]; then
        yay -S python-material-color-utilities swww ttf-tabler-icons python-pywal wlogout gtklock gtklock-playerctl-module gtklock-powerbar-module gtklock-userinfo-module nerd-fonts-inter eww-try-wayland-git gradience fish playerctl starship nautilus gnome-clocks-git gnome-calendar-git gnome-calculator-gtk3 baobab-gtk3 eog-git gnome-font-viewer-git gnome-text-editor-git git
    elif [ "$2" == "-n" ]; then
        yay -S python-material-color-utilities fzf hyprpaper jq
    fi
###

fi
