#!/bin/sh

show_help() {
    printf "
    Usage:
      %s [option]
    
    Options:
      sofa                      sofa
      setup                     Setup sofa 
      update                    Update sofa
    
      wall                      Set wallpaper
      wall -r                   Set random wallpaper
      wall -i <image>           Set wallpaper from image name
      wall -p <path>            Set walpaper from image path (in $HOME)

      color                     Set colors with current wallpaper
      color -m <mode>           Set light/dark mode
      color -c <image> <mode>   Set color from image name and light/dark mode

      full                      Set wallpaper and colors
      full -r                   Set random wallpaper and colors
    \n" "${0##*/}"
}

wall_path=$(jq -r '.wallpath' ~/.sofa/config.json)

if [ "$1" == "--help" ]; then

    show_help
    exit 0

fi

if [ "$1" == "sofa" ]; then

    echo "sofa"

elif [ "$1" == "setup" ]; then

    mkdir -p ~/.sofa
    mkdir -p ~/.sofa/templates
    cp ~/sofa/.sofa/sofa.py ~/.sofa/sofa.py
    cp ~/sofa/.sofa/config.json ~/.sofa/config.json

elif [ "$1" == "update" ]; then

    sudo cp sofa/sofa /usr/local/bin  
    cp ~/sofa/.sofa/sofa.py ~/.sofa/sofa.py

elif [ "$1" == "wall" ]; then

    if [ "$2" == "-r" ]; then

        wall_file=$(ls "$HOME/$wall_path/" | shuf -n 1)

        cp "$HOME/$wall_path/$wall_file" "$HOME/$wall_path/wallpaper"
        pkill hyprpaper && hyprpaper &
        disown %1

    elif [ "$2" == "-i" ]; then

        cp "$HOME/$wall_path/$3" "$HOME/$wall_path/wallpaper"
        pkill hyprpaper && hyprpaper &
        disown %1

    elif [ "$2" == "-p" ]; then

        cp "$HOME/$3" "$HOME/$wall_path/wallpaper"
        pkill hyprpaper && hyprpaper &
        disown %1

    else

        selected_wallpaper=$(find "$HOME/$wall_path" -type f | fzf --preview 'kitty icat {}')

        if [ -n "$selected_wallpaper" ]; then

            cp "$selected_wallpaper" "$HOME/$wall_path/wallpaper"
            pkill hyprpaper && hyprpaper &
            disown %1

        fi
    fi

elif [ "$1" == "color" ]; then

    if [ "$2" == "-c" ]; then
    
        python3 ~/.sofa/sofa.py templater $4
        wal -c
        wal -i "$HOME/$wall_path/$3"
        pywalfox update
        gradience-cli monet --theme $4 -p "$HOME/$wall_path/$3" -n custom
        gradience-cli apply -n custom

    elif [ "$2" == "-m" ]; then

        python3 ~/.sofa/sofa.py templater $3
        wal -c
        wal -i "$HOME/$wall_path/wallpaper"
        pywalfox update
        gradience-cli monet --theme $3 -p "$HOME/$wall_path/wallpaper" -n mode
        gradience-cli apply -n mode

    else

        python3 ~/.sofa/sofa.py templater
        wal -c
        wal -i "$HOME/$wall_path/wallpaper"
        pywalfox update
        gradience-cli monet --theme dark -p "$HOME/$wall_path/wallpaper" -n wallpaper
        gradience-cli apply -n wallpaper

    fi

elif [ "$1" == "full" ]; then

    if [ "$2" == "-r" ]; then

        wall_file=$(ls "$HOME/$wall_path/" | shuf -n 1)

        cp "$HOME/$wall_path/$wall_file" "$HOME/$wall_path/wallpaper"
        pkill hyprpaper && hyprpaper &
        disown %1
        python3 ~/.sofa/sofa.py templater
        wal -c
        wal -i "$HOME/$wall_path/wallpaper"
        pywalfox update
        gradience-cli monet --theme dark -p "$HOME/$wall_path/wallpaper" -n wallpaper
        gradience-cli apply -n wallpaper

    else

        selected_wallpaper=$(find "$HOME/$wall_path" -type f | fzf --preview 'kitty icat {}')

        if [ -n "$selected_wallpaper" ]; then

            cp "$selected_wallpaper" "$HOME/$wall_path/wallpaper"
            pkill hyprpaper && hyprpaper &
            disown %1
            python3 ~/.sofa/sofa.py templater
            wal -c
            wal -i "$HOME/$wall_path/wallpaper"
            pywalfox update
            gradience-cli monet --theme dark -p "$HOME/$wall_path/wallpaper" -n wallpaper
            gradience-cli apply -n wallpaper

        fi
    fi

# Random Utils
elif [ "$1" == "utils" ]; then

    if [ "$2" == "-r" ]; then
        yay -S cbonsai cmatrix neofetch hyfetch pipes.sh cava uwufetch
    elif [ "$2" == "-i" ]; then
        yay -S python-material-color-utilities swww ttf-tabler-icons python-pywal wlogout gtklock gtklock-playerctl-module gtklock-powerbar-module gtklock-userinfo-module nerd-fonts-inter eww-try-wayland-git gradience fish playerctl starship nautilus gnome-clocks-git gnome-calendar-git gnome-calculator-gtk3 baobab-gtk3 eog-git gnome-font-viewer-git gnome-text-editor-git git
    elif [ "$2" == "-n" ]; then
        yay -S python-material-color-utilities fzf hyprpaper jq python-pywal gradience pywalfox
    fi
###

fi